# Generated by Django 4.1.7 on 2023-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='media/', verbose_name='Article Image'),
            preserve_default=False,
        ),
    ]
