# Generated by Django 4.1.7 on 2023-04-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_article_author_alter_article_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='article_image',
        ),
    ]
