# Generated by Django 4.1.7 on 2023-04-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
