# Generated by Django 4.1.7 on 2023-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0010_alter_article_options_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                default=1,
                editable=False,
                max_length=150,
                unique=True,
                verbose_name="Slug",
            ),
            preserve_default=False,
        ),
    ]
